### ISSUE TITLE
Can we just send pre-vote response directly?

### ISSUE THREAD

**Issue by neog24** [etcd-io/raft#230]
Hi @nvanbenschoten , I Look at the raft code below and see that `MsgPreVoteResp` is appended to the `msgsAfterAppend` queue:

https://github.com/etcd-io/raft/blob/61b52be593caec7db60d7229d35c64392e8cbe2f/raft.go#L544-L592

My question is that, since pre-vote does not change any raft state, can we just send this response directly?

**Comment by nvanbenschoten** [comment]
Hi @neog24, we probably can just send `MsgPreVoteResp`, though there is some subtlety. We append to `msgsAfterAppend` for two different reasons. The first is the obvious one — a message needs to change persistent raft state before being sent out. The second is less obvious — a message contains information that is contingent on other in-progress persistent raft state updates.

The handling of `MsgPreVote` is based on the raft log of the peer that is asked to vote. This tail of this raft log may not be durable, so this falls into the second category where the `MsgPreVoteResp` is based on in-progress persistent raft state updates. Since the entire pre-vote protocol is best-effort and it does not provide true mutual exclusion, it's probably ok to send a response based on information that is not persistent.

However, this hasn't been seen to be enough of an issue to warrant making the argument for the safety of doing so. In that way, it's similar to the "Rejected responses" case described in the comment you linked to.

**Comment by neog24** [comment]
@nvanbenschoten got it, thanks for your replay.
